image: node:20

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test
        name: Build and test
        caches:
          - node
          - sonar
        script:
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
          - apt-get update
          - apt-get install -y google-chrome-stable xvfb
          - npm install --quiet
          - npm run test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox

    - step: &analyze-sonarcloud
        name: Sonarqube analysis
        image: maven:3.3.9
        caches:
          - sonar
        script:
          - git fetch --unshallow
          - pipe: sonarsource/sonarcloud-scan:1.2.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
pipelines:
  default:
    - step: *build-test
    - step: *analyze-sonarcloud
  pull-requests:
    '**':
      - step: *build-test
