clone:
  depth: full

definitions:
  services:
    docker:
      memory: 512
    docker-large-memory:
      memory: 5120
      type: docker
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test
        services: [docker-large-memory]
        size: 2x
        image: node:18
        name: Build and test
        caches:
          - node
          - sonar
        script:
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
          - apt-get update
          - apt-get install -y google-chrome-stable xvfb
          - npm install --quiet
          - npm run test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
          - pipe: sonarsource/sonarcloud-scan:3.1.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
    - step: &publish-verdaccio-patch
        services: [docker]
        image: node:18
        name: Publish npm patch
        caches:
          - node
        script:
          - npm install --quiet
          - npm run build
          - cd ./dist/@aseinfo/ngx-evolution-components
          - npm version patch -m "Bump version to %s [skip ci]"
          - npm config set @aseinfo:registry https://npm.aseinfo.net
          - npm config get @aseinfo:registry
          - git push && git push --tags
          - pipe: atlassian/npm-publish:1.0.0
            variables:
              NPM_TOKEN: $NPM_TOKEN

pipelines:
  branches:
    development:
      - step: *build-test
      - step: *publish-verdaccio-patch
