image: node:18

options:
  docker: true
  size: 2x

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test
        name: Build and test
        caches:
          - node
          - sonar
        script:
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
          - apt-get update
          - apt-get install -y google-chrome-stable xvfb
          - npm install --quiet
          - npm run test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
          - pipe: sonarsource/sonarcloud-scan:3.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
    - step: &publish-verdaccio
        name: Publish npm package
        caches:
          - node
        script:
          - npm install --quiet
          - npm install --global verdaccio
          - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          - npm run build
          - cd ./dist/@aseinfo/ngx-evolution-components
          - npm pack
          - npm publish --registry https://npm.aseinfo.net/
pipelines:
  default:
    - step: *build-test
    - step: *publish-verdaccio
  pull-requests:
    '**':
      - step: *build-test
