import { ISmartlistMetadata } from '@aseinfo/ngx-evolution-components/public-api';

export const metaData: ISmartlistMetadata = {
  Code: 'evowave.SolicitudAmonestaciones',
  MultiSelect: true,
  AutogenerateColumns: false,
  NewRecordButtonCode: 'new',
  EditRecordButtonCode: 'edit',
  DeleteRecordButtonCode: 'delete',
  NewRecordButton: {
    Code: 'new',
    ActionURL: '/Create',
    Text: 'Nuevo',
    AlternateText: 'Nueva Solicitud de Amonestación',
    ExecuteLinkAction: true,
    ConfirmationMessage: '',
    CompleteMessage: '',
    ShowText: true,
    ShowImage: true,
    ImageURL: '/Content/Images/Toolbar/add.png',
    VisibleIndex: 10,
    Visible: true,
    Visibility: 'Visible',
    TextVisibility: 'Visible',
    ImageVisibility: 'Visible',
    IsExportToExcelButton: false,
    CheckForSelectedRecords: false,
    IsRouteUrl: false,
    ControllerArea: '',
    ControllerName: '',
    ControllerAction: 'Create',
  },
  EditRecordButton: {
    Code: 'edit',
    ActionURL: '/Edit',
    Text: 'Editar',
    AlternateText: 'Editar la Solicitud de Amonestación',
    ExecuteLinkAction: true,
    ConfirmationMessage: '',
    CompleteMessage: '',
    ShowText: true,
    ShowImage: true,
    ImageURL: '/Content/Images/Toolbar/edit.png',
    VisibleIndex: 20,
    Visible: true,
    Visibility: 'Visible',
    TextVisibility: 'Visible',
    ImageVisibility: 'Visible',
    IsExportToExcelButton: false,
    CheckForSelectedRecords: true,
    IsRouteUrl: false,
    ControllerArea: '',
    ControllerName: '',
    ControllerAction: 'Edit',
  },
  DeleteRecordButton: {
    Code: 'delete',
    ActionURL: '/Delete',
    Text: 'Eliminar',
    AlternateText: 'Eliminar la Solicitud de Amonestación',
    ExecuteLinkAction: false,
    ConfirmationMessage:
      '¿Está seguro que desea eliminar la solicitud de Amonestación?',
    CompleteMessage: '',
    ShowText: true,
    ShowImage: true,
    ImageURL: '/Content/Images/Toolbar/delete.png',
    VisibleIndex: 30,
    Visible: true,
    Visibility: 'Visible',
    TextVisibility: 'Visible',
    ImageVisibility: 'Visible',
    IsExportToExcelButton: false,
    CheckForSelectedRecords: true,
    IsRouteUrl: false,
    ControllerArea: '',
    ControllerName: '',
    ControllerAction: 'Delete',
  },
  AutomaticBinding: true,
  Height: 'Auto',
  ShowFilter: true,
  ShowGroupPanel: true,
  ShowLargeDatasetWarning: false,
  Buttons: [
    {
      Code: 'new',
      ActionURL: '/Create',
      Text: 'Nuevo',
      AlternateText: 'Nueva Solicitud de Amonestación',
      ExecuteLinkAction: true,
      ConfirmationMessage: '',
      CompleteMessage: '',
      ShowText: true,
      ShowImage: true,
      ImageURL: '/Content/Images/Toolbar/add.png',
      VisibleIndex: 10,
      Visible: true,
      Visibility: 'Visible',
      TextVisibility: 'Visible',
      ImageVisibility: 'Visible',
      IsExportToExcelButton: false,
      CheckForSelectedRecords: false,
      IsRouteUrl: false,
      ControllerArea: '',
      ControllerName: '',
      ControllerAction: 'Create',
    },
    {
      Code: 'edit',
      ActionURL: '/Edit',
      Text: 'Editar',
      AlternateText: 'Editar la Solicitud de Amonestación',
      ExecuteLinkAction: true,
      ConfirmationMessage: '',
      CompleteMessage: '',
      ShowText: true,
      ShowImage: true,
      ImageURL: '/Content/Images/Toolbar/edit.png',
      VisibleIndex: 20,
      Visible: true,
      Visibility: 'Visible',
      TextVisibility: 'Visible',
      ImageVisibility: 'Visible',
      IsExportToExcelButton: false,
      CheckForSelectedRecords: true,
      IsRouteUrl: false,
      ControllerArea: '',
      ControllerName: '',
      ControllerAction: 'Edit',
    },
    {
      Code: 'delete',
      ActionURL: '/Delete',
      Text: 'Eliminar',
      AlternateText: 'Eliminar la Solicitud de Amonestación',
      ExecuteLinkAction: false,
      ConfirmationMessage:
        '¿Está seguro que desea eliminar la solicitud de Amonestación?',
      CompleteMessage: '',
      ShowText: true,
      ShowImage: true,
      ImageURL: '/Content/Images/Toolbar/delete.png',
      VisibleIndex: 30,
      Visible: true,
      Visibility: 'Visible',
      TextVisibility: 'Visible',
      ImageVisibility: 'Visible',
      IsExportToExcelButton: false,
      CheckForSelectedRecords: true,
      IsRouteUrl: false,
      ControllerArea: '',
      ControllerName: '',
      ControllerAction: 'Delete',
    },
    {
      Code: 'initflujo',
      ActionURL: '/InicializaFlujoAutorizacion',
      Text: 'Enviar a Autorización',
      AlternateText: '',
      ExecuteLinkAction: false,
      ConfirmationMessage:
        '¿Está seguro que desea enviar a autorización la solicitud de amonestación?',
      CompleteMessage: '',
      ShowText: true,
      ShowImage: true,
      ImageURL: '/Content/Images/Toolbar/send_authorize.png',
      VisibleIndex: 40,
      Visible: true,
      Visibility: 'Visible',
      TextVisibility: 'Visible',
      ImageVisibility: 'Visible',
      IsExportToExcelButton: false,
      CheckForSelectedRecords: true,
      IsRouteUrl: false,
      ControllerArea: '',
      ControllerName: '',
      ControllerAction: 'InicializaFlujoAutorizacion',
    },
  ],
  Columns: [
    {
      Code: 'amo_codigo',
      FieldName: 'amo_codigo',
      PropertyName: 'amo_codigo',
      Header: 'amo_codigo',
      IsPrimaryKey: true,
      FieldDescriptor: 'int',
      Visible: false,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 10,
      Width: 'Auto',
      Wrap: false,
      Format: 'N0',
    },
    {
      Code: 'cia_descripcion',
      FieldName: 'cia_descripcion',
      PropertyName: 'cia_descripcion',
      Header: 'Compañia',
      IsPrimaryKey: false,
      FieldDescriptor: 'string',
      Visible: true,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 20,
      Width: 'Auto',
      Wrap: false,
    },
    {
      Code: 'exp_apellidos_nombres1',
      FieldName: 'exp_apellidos_nombres1',
      PropertyName: 'exp_apellidos_nombres1',
      Header: 'Empleado',
      IsPrimaryKey: false,
      FieldDescriptor: 'string',
      Visible: true,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 30,
      Width: 'Auto',
      Wrap: false,
    },
    {
      Code: 'amo_fecha_infraccion',
      FieldName: 'amo_fecha_infraccion',
      PropertyName: 'amo_fecha_infraccion',
      Header: 'Fecha Infracción',
      IsPrimaryKey: false,
      FieldDescriptor: 'date',
      Visible: true,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 40,
      Width: 'Auto',
      Wrap: false,
      Format: 'g',
    },
    {
      Code: 'tam_descripcion',
      FieldName: 'tam_descripcion',
      PropertyName: 'tam_descripcion',
      Header: 'Tipo',
      IsPrimaryKey: false,
      FieldDescriptor: 'string',
      Visible: true,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 50,
      Width: 'Auto',
      Wrap: false,
    },
    {
      Code: 'cau_descripcion',
      FieldName: 'cau_descripcion',
      PropertyName: 'cau_descripcion',
      Header: 'Causa',
      IsPrimaryKey: false,
      FieldDescriptor: 'string',
      Visible: true,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 60,
      Width: 'Auto',
      Wrap: false,
    },
    {
      Code: 'exp_apellidos_nombres2',
      FieldName: 'exp_apellidos_nombres2',
      PropertyName: 'exp_apellidos_nombres2',
      Header: 'Solicitante',
      IsPrimaryKey: false,
      FieldDescriptor: 'string',
      Visible: true,
      AlternateText: '',
      HorizontalAlign: 'Left',
      VerticalAlign: 'Automatic',
      VisibleIndex: 70,
      Width: 'Auto',
      Wrap: false,
    },
  ],
  LocalizedStrings: [
    {
      Key: '{EmptyDataSetMessage}',
      Translation:
        'No existen registros que mostrar de acuerdo al criterio de búsqueda especificado.',
    },
    {
      Key: '{EliminarCriterioBusqueda}',
      Translation: 'Eliminar criterio de búsqueda especificado',
    },
    {
      Key: '{Buscar}',
      Translation: 'Buscar',
    },
    {
      Key: '{NoRecordsSelectedMessage}',
      Translation:
        'Debe seleccionar al menos un registro para ejecutar la acción',
    },
    {
      Key: '{ExportaAExcelTooltip}',
      Translation: 'Exportar a Microsoft Excel',
    },
    {
      Key: '{AdvancedSearchLocalizationKey}',
      Translation: 'Búsqueda Avanzada',
    },
    {
      Key: '{QueryBuilderShowErrorsLocalizationKey}',
      Translation:
        'Existen errores en la especificación de los criterios de búsqueda',
    },
    {
      Key: '{Si}',
      Translation: 'Sí',
    },
    {
      Key: '{No}',
      Translation: 'No',
    },
  ],
  ShowExportToExcelButton: true,
  AlmacenaInformacionPersonalizacion: false,
};
